from __future__ import annotations

import json
from dataclasses import dataclass
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from typing import Any, Optional
from urllib import error, request

from psycopg import connect

from env_config import get_env


@dataclass
class SupabaseConfig:
    url: str
    publishable_key: str
    service_role_key: str
    database_url: str
    alerts_table: str = "alerts"

    @classmethod
    def from_env(cls) -> Optional["SupabaseConfig"]:
        url = get_env("SUPABASE_URL", "").strip()
        publishable_key = (
            get_env("SUPABASE_PUBLISHABLE_KEY", "").strip()
            or get_env("SUPABASE_ANON_KEY", "").strip()
        )
        service_role_key = get_env("SUPABASE_SERVICE_ROLE_KEY", "").strip()
        database_url = _normalize_database_url(
            get_env("DIRECT_URL", "").strip()
            or get_env("DATABASE_URL", "").strip()
            or get_env("SUPABASE_DB_URL", "").strip()
        )
        table = get_env("SUPABASE_ALERTS_TABLE", "alerts").strip() or "alerts"
        if not url:
            return None
        return cls(
            url=url.rstrip("/"),
            publishable_key=publishable_key,
            service_role_key=service_role_key,
            database_url=database_url,
            alerts_table=table,
        )


def _normalize_database_url(raw_url: str) -> str:
    if not raw_url:
        return ""
    parts = urlsplit(raw_url)
    filtered_query = [
        (key, value)
        for key, value in parse_qsl(parts.query, keep_blank_values=True)
        if key.lower() not in {"uselibpqcompat", "pgbouncer"}
    ]
    return urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(filtered_query), parts.fragment)
    )


class DatabaseAlertPublisher:
    def __init__(self, config: SupabaseConfig) -> None:
        self.config = config

    def ensure_table(self) -> None:
        with connect(self.config.database_url) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"""
                    create table if not exists public.{self.config.alerts_table} (
                        id bigint generated by default as identity primary key,
                        track_id bigint not null,
                        timestamp timestamptz not null,
                        confidence double precision not null,
                        explanation text not null,
                        snapshot text,
                        created_at timestamptz not null default timezone('utc', now())
                    )
                    """
                )
                cur.execute(
                    f"alter table if exists public.{self.config.alerts_table} add column if not exists explanation text"
                )
                cur.execute(
                    f"alter table if exists public.{self.config.alerts_table} add column if not exists confidence double precision"
                )
                cur.execute(
                    f"alter table if exists public.{self.config.alerts_table} add column if not exists snapshot text"
                )
                cur.execute(
                    f"alter table if exists public.{self.config.alerts_table} add column if not exists timestamp timestamptz"
                )
                cur.execute(
                    f"alter table if exists public.{self.config.alerts_table} add column if not exists created_at timestamptz not null default timezone('utc', now())"
                )
            conn.commit()

    def publish(self, record: dict[str, Any]) -> dict[str, Any]:
        self.ensure_table()
        with connect(self.config.database_url) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"""
                    insert into public.{self.config.alerts_table}
                    (track_id, timestamp, confidence, explanation, snapshot)
                    values (%s, %s, %s, %s, %s)
                    returning alert_id, track_id, timestamp, confidence, explanation, snapshot, created_at
                    """,
                    (
                        str(record["track_id"]),
                        record["timestamp"],
                        record["confidence"],
                        record["explanation"],
                        record["snapshot"],
                    ),
                )
                row = cur.fetchone()
            conn.commit()
        return {"ok": True, "mode": "database", "row": row}


class DatabaseAlertReader:
    def __init__(self, config: SupabaseConfig) -> None:
        self.config = config

    def fetch_recent(self, limit: int = 25) -> list[dict[str, Any]]:
        with connect(self.config.database_url) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"""
                    select
                        alert_id,
                        track_id,
                        confidence,
                        explanation,
                        snapshot,
                        timestamp,
                        priority,
                        status,
                        alert_level,
                        created_at
                    from public.{self.config.alerts_table}
                    order by created_at desc nulls last, timestamp desc nulls last, alert_id desc
                    limit %s
                    """,
                    (limit,),
                )
                rows = cur.fetchall()
        return [
            {
                "alert_id": row[0],
                "track_id": row[1],
                "confidence": float(row[2]) if row[2] is not None else None,
                "explanation": row[3],
                "snapshot": row[4],
                "timestamp": row[5].isoformat() if row[5] else None,
                "priority": row[6],
                "status": row[7],
                "alert_level": row[8],
                "created_at": row[9].isoformat() if row[9] else None,
            }
            for row in rows
        ]


class SupabaseAlertPublisher:
    def __init__(self, config: SupabaseConfig) -> None:
        self.config = config

    def publish(self, record: dict[str, Any]) -> dict[str, Any]:
        payload = json.dumps(record).encode("utf-8")
        endpoint = f"{self.config.url}/rest/v1/{self.config.alerts_table}"
        req = request.Request(
            endpoint,
            data=payload,
            headers={
                "apikey": self.config.service_role_key or self.config.publishable_key,
                "Authorization": f"Bearer {self.config.service_role_key or self.config.publishable_key}",
                "Content-Type": "application/json",
                "Prefer": "return=representation",
            },
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=10) as response:
                body = response.read().decode("utf-8")
                rows = json.loads(body) if body else []
                return {"ok": True, "rows": rows}
        except error.HTTPError as exc:
            details = exc.read().decode("utf-8", errors="replace")
            return {"ok": False, "status": exc.code, "error": details}
        except error.URLError as exc:
            return {"ok": False, "error": str(exc.reason)}


class SupabaseAlertReader:
    def __init__(self, config: SupabaseConfig) -> None:
        self.config = config

    def fetch_recent(self, limit: int = 25) -> list[dict[str, Any]]:
        endpoint = (
            f"{self.config.url}/rest/v1/{self.config.alerts_table}"
            f"?select=alert_id,track_id,confidence,explanation,snapshot,timestamp,priority,status,alert_level,created_at"
            f"&order=created_at.desc.nullslast,timestamp.desc.nullslast,alert_id.desc&limit={int(limit)}"
        )
        req = request.Request(
            endpoint,
            headers={
                "apikey": self.config.service_role_key or self.config.publishable_key,
                "Authorization": f"Bearer {self.config.service_role_key or self.config.publishable_key}",
                "Content-Type": "application/json",
            },
            method="GET",
        )
        with request.urlopen(req, timeout=10) as response:
            body = response.read().decode("utf-8")
        rows = json.loads(body) if body else []
        return rows
