create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    track_id bigint not null,
    timestamp timestamptz not null,
    confidence double precision not null,
    explanation text not null,
    snapshot text,
    created_at timestamptz not null default timezone('utc', now())
);
