-- Supabase required setup for eye_dentify
-- Run AFTER: 2026_02_04_alert_lifecycle.sql

create extension if not exists "pgcrypto";

-- Core tables
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  full_name text,
  role text default 'user',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.missing_persons (
  missing_person_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  age integer,
  gender text,
  height_cm numeric(5,2),
  height_range_min numeric(5,2),
  height_range_max numeric(5,2),
  last_seen_location text,
  last_seen_datetime timestamptz,
  clothing_description text,
  additional_notes text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.media (
  media_id bigint generated by default as identity primary key,
  missing_person_id bigint not null references public.missing_persons(missing_person_id) on delete cascade,
  file_path text not null,
  file_type text default 'image',
  file_size_bytes bigint,
  description text,
  upload_timestamp timestamptz default now()
);

create table if not exists public.detections (
  detection_id bigint generated by default as identity primary key,
  missing_person_id bigint references public.missing_persons(missing_person_id) on delete set null,
  camera_id bigint,
  camera_id_text text,
  track_id text,
  embedding double precision[],
  confidence numeric,
  snapshot_url text,
  bbox jsonb,
  detection_timestamp timestamptz default now(),
  face_score numeric,
  clothing_score numeric,
  verified boolean default false,
  verified_by uuid references auth.users(id) on delete set null,
  verified_at timestamptz,
  source text default 'camera'
);

create table if not exists public.alerts (
  alert_id bigint generated by default as identity primary key,
  detection_id bigint references public.detections(detection_id) on delete set null,
  user_id uuid references auth.users(id) on delete cascade,
  alert_timestamp timestamptz default now(),
  message text,
  status text default 'pending_verification',
  priority text default 'medium',
  read_at timestamptz,
  acknowledged_at timestamptz,
  dismissed_at timestamptz,
  fcm_token text,
  sightings_count integer default 1,
  first_seen_time timestamptz default now(),
  last_seen_time timestamptz default now(),
  alert_level text default 'preliminary',
  camera_id text,
  camera_id_text text,
  track_id text,
  confidence numeric,
  ai_summary text
);

create table if not exists public.system_logs (
  log_id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action_type text not null,
  action_details text,
  ip_address text,
  "timestamp" timestamptz default now()
);

-- Required cameras table per spec
create table if not exists public.cameras (
  id uuid primary key default gen_random_uuid(),
  name text,
  location text,
  lat double precision,
  lng double precision,
  status text default 'active',
  api_key text,
  created_at timestamptz default now()
);

create table if not exists public.device_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  token text unique not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Ensure lifecycle columns required by ingest/alerts exist
alter table public.alerts
  add column if not exists sightings_count integer default 1,
  add column if not exists first_seen_time timestamptz default now(),
  add column if not exists last_seen_time timestamptz default now(),
  add column if not exists alert_level text default 'preliminary',
  add column if not exists camera_id_text text,
  add column if not exists track_id text,
  add column if not exists confidence numeric;

alter table public.detections
  add column if not exists camera_id_text text,
  add column if not exists track_id text,
  add column if not exists embedding double precision[],
  add column if not exists confidence numeric,
  add column if not exists snapshot_url text,
  add column if not exists bbox jsonb,
  add column if not exists detection_timestamp timestamptz default now(),
  add column if not exists face_score numeric,
  add column if not exists clothing_score numeric;

create index if not exists idx_detections_track_camera on public.detections(track_id, camera_id_text);
create index if not exists idx_alerts_track_camera on public.alerts(track_id, camera_id_text);
create index if not exists idx_alerts_status on public.alerts(status);

-- RLS
alter table public.users enable row level security;
alter table public.missing_persons enable row level security;
alter table public.media enable row level security;
alter table public.detections enable row level security;
alter table public.alerts enable row level security;
alter table public.system_logs enable row level security;
alter table public.cameras enable row level security;
alter table public.device_tokens enable row level security;

drop policy if exists missing_persons_owner_all on public.missing_persons;
create policy missing_persons_owner_all
on public.missing_persons
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists alerts_owner_all on public.alerts;
create policy alerts_owner_all
on public.alerts
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists detections_service_role_all on public.detections;
create policy detections_service_role_all
on public.detections
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists alerts_service_role_all on public.alerts;
create policy alerts_service_role_all
on public.alerts
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

